# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4f263fe63adfcab63c0b73940991383311744765183b67bfcb7940519464e8e1717ac50bd9daa25e7dd66463c7da97a6ce8d5013da63bf5beb693c29e98579

test:
  secret_key_base: 8370f30f34d3f7effbfd973b49ca8948331c8fb74ceca1537f4093ece367842615634e739f8b0010bad6a8554f8879929ce45545e047a095ba5e4e050560ec02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
